### ISSUE TITLE
Team Contributions Doc

### ISSUE THREAD

**Issue by sunilgowda67** [akshay0828/Spiceland-12-12-2022#4]
Contributions of each and every team members for the projects must be shared in doc/excel

**Comment by 12bharu** [comment]
individual contrubution documentation 
Folder_Name:-Individual_Contribution folder
issue no-#4

**Comment by sunilgowda67** [comment]
Details are not clear and upload single document which has contribution details of all team members.
Mention the details about individual contribution and responsibility taken to accomplish the project.
(do not use screen shots of jira)

**Comment by Yeshaswini2000** [comment]
For Issue #4 file changed
File name: -Individual Contribution of team 5.pdf

**Comment by sunilgowda67** [comment]
closed
