### ISSUE TITLE
Project Deployment

### ISSUE THREAD

**Issue by sunilgowda67** [akshay0828/Spiceland-12-12-2022#5]
Add deployment steps as part of Readme.md or as separate document

**Comment by akshay0828** [comment]
Steps to deploy Spring_boot application on Apache Tomcat-Issue-no #5 resolved
Document URL:  https://github.com/akshay0828/Spiceland-12-12-2022/blob/main/Tomcat_deployment.pdf

**Comment by sunilgowda67** [comment]
Reviewed and Closed
